import Head from "next/head";
import { Inter } from "next/font/google";
import HomeCarousel from "@/frontend/components/Carousel";
import ChooseUs from "@/frontend/components/WhyChooseus";
import OurServices from "@/frontend/components/OurServices";
import SeiMap from "@/frontend/components/Map";
import Button from "react-bootstrap/Button";
import Modal from "react-bootstrap/Modal";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

function MyVerticallyCenteredModal(props) {
  return (
    <Modal
      {...props}
      size="lg"
      aria-labelledby="contained-modal-title-vcenter"
      centered
    >
      <Modal.Header closeButton>
        <Modal.Title id="contained-modal-title-vcenter">
          SEI INSTITUTE
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <h4>Admission For Bridge Course 2080 BS</h4>
        <p style={{color:"Red"}}>
          " We want to let you know that our application is currently in the
          development process, but we are working hard to ensure that it meets
          your expectations. Please stay with us, and we will keep you updated
          on our progress.
        </p>
      </Modal.Body>
    </Modal>
  );
}

export default function Home() {
  const [modalShow, setModalShow] = useState(false);
  useEffect(() => {
    setModalShow(true);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          width: "90%",
          margin: "auto",
          marginTop: "2rem",
        }}
      >
        <MyVerticallyCenteredModal
          show={modalShow}
          onHide={() => setModalShow(false)}
        />
        <HomeCarousel />
        <ChooseUs />
        <OurServices />
        <SeiMap />
      </main>
    </>
  );
}
